[package]
name = "leo-parser-lossless"
version = "3.4.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Lossless syntax tree parser for the Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2024"

[dependencies]
# leo dependencies
leo-errors      = { workspace = true }
leo-span        = { workspace = true }
# third party dependencies
itertools       = { workspace = true }
lalrpop-util    = { workspace = true }
logos           = { workspace = true }
regex           = { workspace = true }

[build-dependencies]
# third party dependencies
lalrpop = { workspace = true }
