[package]
name = "leo-core"
version = "1.6.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Core library functions for the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.65"

[lib]
path = "src/lib.rs"

[dependencies.leo-ast]
path = "../ast"
version = "1.6.3"

[dependencies.leo-errors]
path = "../../errors"
version = "1.6.3"

[dependencies.leo-span]
path = "../span"
version = "1.6.3"
