[package]
name = "leo-compiler"
version = "2.6.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Compiler for Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2024"
rust-version = "1.85.1"

[dependencies.leo-ast]
workspace = true

[dependencies.leo-errors]
workspace = true

[dependencies.leo-passes]
workspace = true

[dependencies.leo-parser]
workspace = true

[dependencies.leo-span]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.aleo-std-storage]
workspace = true

[dependencies.rand_chacha]
workspace = true

[dependencies.sha2]
version = "0.10"

[dependencies.snarkvm]
workspace = true

[dependencies.indexmap]
workspace = true

[dependencies.serde_json]
workspace = true

[dev-dependencies.leo-disassembler]
path = "../../utils/disassembler"

[dev-dependencies.leo-test-framework]
workspace = true

[dev-dependencies.itertools]
workspace = true

[dev-dependencies.snarkvm]
workspace = true

[dev-dependencies.serde]
workspace = true

[dev-dependencies.regex]
version = "1.11.1"

[dev-dependencies.serial_test]
workspace = true

[dev-dependencies.tempfile]
workspace = true

[features]
default = [ ]
ci_skip = [ "leo-ast/ci_skip" ]
