[package]
name = "leo-compiler"
version = "1.8.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Compiler for Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.69"

[dependencies.leo-ast]
path = "../ast"
version = "1.8.2"

[dependencies.leo-errors]
path = "../../errors"
version = "1.8.2"

[dependencies.leo-passes]
path = "../passes"
version = "1.8.2"

[dependencies.leo-parser]
path = "../parser"
version = "1.8.2"

[dependencies.leo-span]
path = "../span"
version = "1.8.2"

[dependencies.sha2]
version = "0.10"

[dev-dependencies.leo-test-framework]
path = "../../tests/test-framework"
version = "1.4.0"

[dev-dependencies.rand]
version = "0.8"
default-features = false

[dev-dependencies.snarkvm]
workspace = true
features = [ "circuit", "console" ]

[dev-dependencies.regex]
version = "1.8.4"

[dev-dependencies.serde]
version = "1.0.164"
features = [ "derive" ]

[dev-dependencies.serde_yaml]
version = "0.8.25"

[dev-dependencies.tempfile]
version = "3.6"

[features]
default = [ ]
ci_skip = [ "leo-ast/ci_skip" ]
