[package]
name = "leo-passes"
version = "3.4.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Compiler passes for the Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
# leo dependencies
leo-abi-types = { workspace = true }
leo-ast       = { workspace = true }
leo-errors    = { workspace = true }
leo-package   = { workspace = true }
leo-span      = { workspace = true }
# third party dependencies
anyhow        = { workspace = true }
base62        = { workspace = true }
indexmap      = { workspace = true }
itertools     = { workspace = true }
num-traits    = { workspace = true }
regex         = { workspace = true }
sha2          = { workspace = true }
serde         = { workspace = true }
serde_json    = { workspace = true }
snarkvm       = { workspace = true }

[dev-dependencies]
# leo dependencies
leo-parser         = { workspace = true }
leo-test-framework = { workspace = true }
# third party dependencies
paste              = { workspace = true }
serial_test        = { workspace = true }
