[package]
name = "leo-passes"
version = "3.1.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Compiler passes for the Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2024"
rust-version = "1.88.0"

[lib]
path = "src/lib.rs"

[dependencies.base62]
workspace = true

[dependencies.snarkvm]
workspace = true

[dependencies.leo-ast]
workspace = true

[dependencies.leo-errors]
workspace = true

[dependencies.leo-package]
workspace = true

[dependencies.leo-parser]
workspace = true

[dependencies.leo-span]
workspace = true

[dependencies.indexmap]
workspace = true

[dependencies.itertools]
workspace = true

[dependencies.num-traits]
version = "0.2.19"

[dependencies.regex]
workspace = true

[dependencies.sha2]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true
