[package]
name = "leo-passes"
version = "1.6.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Compiler passes for the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.65"

[lib]
path = "src/lib.rs"

[dependencies.indexmap]
version = "1.9"

[dependencies.leo-ast]
path = "../ast"
version = "1.6.1"

[dependencies.leo-errors]
path = "../../errors"
version = "1.6.1"

[dependencies.leo-parser]
path = "../parser"
version = "1.6.1"

[dependencies.leo-span]
path = "../span"
version = "1.6.1"

[dependencies.leo-core]
path = "../core"
version = "1.6.1"

[dependencies.itertools]
version = "0.10.5"

[dependencies.num-traits]
version = "0.2.15"
