[package]
name = "leo-state"
version = "1.0.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "State parser of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.leo-input]
path = "../input"
version = "1.0.7"

[dependencies.leo-ast]
path = "../ast"
version = "1.0.7"

[dependencies.snarkvm-algorithms]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
default-features = false

[dependencies.snarkvm-curves]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
default-features = false

[dependencies.snarkvm-dpc]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
default-features = false

[dependencies.snarkvm-errors]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
default-features = false

[dependencies.snarkvm-models]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
default-features = false

[dependencies.snarkvm-objects]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
default-features = false

[dependencies.snarkvm-utilities]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"

[dependencies.indexmap]
version = "1.6.1"
features = [ "serde-1" ]

[dependencies.rand]
version = "0.7"

[dependencies.rand_xorshift]
version = "0.2"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.snarkvm-storage]
git = "https://github.com/AleoHQ/snarkVM.git"
rev = "0e2f38f"
version = "0.0.1"
