[package]
name = "leo-state"
version = "1.0.1"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "State parser of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = ["aleo", "cryptography", "leo", "programming-language", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "web-programming"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
leo-input = { path = "../input", version = "1.0.1" }
leo-typed = { path = "../typed", version = "1.0.1" }

snarkos-algorithms = { version = "1.1.3", default-features = false }
snarkos-curves = { version = "1.1.3", default-features = false }
snarkos-dpc = {  version = "1.1.3", default-features = false }
snarkos-errors = { version = "1.1.3", default-features = false }
snarkos-models =  { version = "1.1.3", default-features = false }
snarkos-objects = { version = "1.1.3", default-features = false }
snarkos-utilities = { version = "1.1.3" }

rand = { version = "0.7" }
rand_xorshift = { version = "0.2" }
thiserror = { version = "1.0" }

[dev-dependencies]
snarkos-storage = { version = "1.1.4" }
