[package]
name = "leo-linter"
version = "3.3.1"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Linter for Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2024"
rust-version = "1.88.0"

[dependencies.leo-ast]
workspace = true

[dependencies.leo-errors]
workspace = true

[dependencies.leo-compiler]
workspace = true

[dependencies.leo-parser]
workspace = true

[dependencies.leo-parser-lossless]
workspace = true

[dependencies.leo-passes]
workspace = true

[dependencies.leo-span]
workspace = true

[dependencies.indexmap]
workspace = true

[dependencies.walkdir]
workspace = true

[dev-dependencies.snarkvm]
workspace = true

[dev-dependencies.serial_test]
workspace = true

[dev-dependencies.leo-test-framework]
workspace = true
