[package]
name = "leo-errors"
version = "1.5.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Errors of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.63"

[dependencies.leo-span]
path = "../compiler/span"
version = "1.5.3"

[dependencies.anyhow]
version = "1.0"

[dependencies.backtrace]
version = "0.3.66"

[dependencies.colored]
version = "2.0.0"

[dependencies.color-backtrace]
version = "0.5.1"

[dependencies.derivative]
version = "2.2.0"

[dependencies.serde]
version = "1.0.147"
features = [ "derive", "rc" ]

[dependencies.thiserror]
version = "1.0.37"
