[package]
name = "leo-errors"
version = "2.2.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Errors for the Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.69"

[dependencies.leo-span]
path = "../compiler/span"
version = "2.2.0"

[dependencies.anyhow]
version = "1.0"

[dependencies.backtrace]
version = "0.3.73"

[dependencies.colored]
version = "2.0.4"

[dependencies.color-backtrace]
version = "0.6.1"

[dependencies.derivative]
version = "2.2.0"

[dependencies.reqwest]
version = "0.12.7"

[dependencies.serde]
version = "1.0.209"
features = [ "derive", "rc" ]

[dependencies.thiserror]
version = "1.0.63"
