[package]
name = "leo-test-framework"
version = "1.5.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Leo testing framework"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dependencies.serde_yaml]
version = "0.8"

# List of dependencies for tgc binary;

[dependencies.leo-ast]
path = "../ast"
version = "1.5.2"

[dependencies.leo-ast-passes]
path = "../ast-passes"
version = "1.5.2"

[dependencies.leo-parser]
path = "../parser"
version = "1.5.2"

[dependencies.leo-imports]
path = "../imports"
version = "1.5.2"

[dependencies.leo-asg]
path = "../asg"
version = "1.5.2"

[dependencies.leo-compiler]
path = "../compiler"
version = "1.5.2"

[dependencies.structopt]
version = "0.3"

# List of dependencies for errcov
[dependencies.leo-errors]
path = "../errors"
version = "1.5.3"

[dependencies.regex]
version = "1.5"