[package]
name = "leo-parser"
version = "1.6.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Parser for the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.65"

[dependencies.leo-ast]
path = "../ast"
version = "1.6.3"

[dependencies.leo-errors]
path = "../../errors"
version = "1.6.3"

[dependencies.leo-span]
path = "../span"
version = "1.6.3"

[dependencies.snarkvm-console]
workspace = true
default-features = false
features = [ "account", "network" ]

[dependencies.clap]
version = "4.1"
features = [ "derive" ]

[dependencies.indexmap]
version = "1.9"

[dependencies.lazy_static]
version = "1.3.0"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.smallvec]
version = "1.10"

[dependencies.tracing]
version = "0.1"

[dev-dependencies.leo-test-framework]
path = "../../tests/test-framework"
version = "1.4.0"

[dev-dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.serde_yaml]
version = "0.8"

[features]
default = [ ]
ci_skip = [ ]
