[package]
name = "leo-parser"
version = "3.4.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Translating from the lossless syntax tree to the AST for the Leo language language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2024"

[dependencies]
# leo dependencies
leo-ast             = { workspace = true }
leo-errors          = { workspace = true }
leo-parser-rowan    = { workspace = true }
leo-span            = { workspace = true }
# third party dependencies
indexmap            = { workspace = true }
itertools           = { workspace = true }
snarkvm             = { workspace = true }

[dev-dependencies]
# leo dependencies
leo-test-framework  = { workspace = true }
# third party dependencies
serial_test         = { workspace = true }
