[package]
name = "leo-span"
version = "2.2.0"
authors = [ "The Leo Team <leo@provable.com>" ]
description = "Span handling for the Leo programming language"
homepage = "https://leo-lang.org"
repository = "https://github.com/ProvableHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.69"

[dependencies.indexmap]
version = "1.9"
features = [ "serde" ]

[dependencies.fxhash]
version = "0.2.1"

[dependencies.scoped-tls]
version = "1.0.1"

[dependencies.serde]
version = "1.0.210"
features = [ "derive", "rc" ]
