[package]
name = "leo-ast"
version = "1.10.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Abstract syntax tree (AST) for the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "compilers", "cryptography", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"
rust-version = "1.69"

[dependencies.leo-errors]
path = "../../errors"
version = "=1.10.0"

[dependencies.leo-span]
path = "../span"
version = "=1.10.0"

[dependencies.indexmap]
version = "1.9"
features = [ "serde-1" ]

[dependencies.itertools]
version = "0.12.0"

[dependencies.serde]
version = "1.0"
features = [ "derive", "rc" ]

[dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dependencies.smallvec]
version = "1.11.2"
features = [ "serde" ]

[dev-dependencies.criterion]
version = "0.5"

[features]
default = [ ]
ci_skip = [ ]
